Change dispatch

diff --git a/.github/workflows/trigger.yml b/.github/workflows/trigger.yml
--- a/.github/workflows/trigger.yml
+++ b/.github/workflows/trigger.yml
@@ -27,10 +27,55 @@ jobs:
     - name: Trigger remote/local Github Action
       # You may pin to the exact commit or the version.
       # uses: kumarabd/trigger-remote-action@b1a19e69663596615eb033be4d50069044d97fb3
-      uses: kumarabd/trigger-remote-action@master
       with:
         # name of the action
         name: Trigger
         # name of the repo that has the action
         repo: t-demo-org/triggered-repo
         token: "${{ secrets.GIT_TOKEN }}"
+        ref: $GITHUB_REF
+      run: |
+            GITHUB_API_URL="api.github.com"
+
+            if [[ -z "$GITHUB_REPOSITORY" ]]; then
+              echo "Missing GITHUB_REPOSITORY env variable"
+              exit 1
+            fi
+
+            REPO=$GITHUB_REPOSITORY
+            if ! [[ -z ${INPUT_REPO} ]]; then
+              REPO=$INPUT_REPO
+            fi
+
+            NAME=$INPUT_NAME
+            if ! [[ -z ${INPUT_NAME} ]]; then
+              NAME=$INPUT_NAME
+            fi
+
+            # Optional personal access token for external repository
+            TOKEN=$GITHUB_TOKEN
+            if ! [[ -z ${INPUT_TOKEN} ]]; then
+              TOKEN=$INPUT_TOKEN
+            fi
+            REF=$GITHUB_REF
+            if ! [[ -z ${INPUT_REF} ]]; then
+              REF=$INPUT_REF
+            fi
+
+            WORKFLOW_API_URL="https://$GITHUB_API_URL/repos/$REPO/actions/workflows"
+            RELEASE_DATA=$(curl -H "Authorization: token $TOKEN" $WORKFLOW_API_URL)
+            ACTION_ID=$(echo $RELEASE_DATA | jq -r ".workflows[] | select(.name == \"$NAME\").id")
+
+            if [[ "$ACTION_ID" == "" ]]; then
+              echo "[!] Action not found"
+              exit 1
+            fi
+
+            curl \
+              -X POST \
+              -H "Authorization: token $TOKEN" \
+              -H "Accept: application/vnd.github.v3+json" \
+              $WORKFLOW_API_URL/$ACTION_ID/dispatches \
+              -d '{"ref":"${REF}","inputs": {"version":"'${INPUT_VERSION}'","revision":"'${REVISION}'"}}'
+
+            echo "Triggered: "$ACTION_ID
